// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDMvw1aJ2xISCvZVifdj2ws_CqCYti-gY',
    appId: '1:415358360776:web:54d96b476dff8d1c8d59fd',
    messagingSenderId: '415358360776',
    projectId: 'food-delivery-69efb',
    authDomain: 'food-delivery-69efb.firebaseapp.com',
    storageBucket: 'food-delivery-69efb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcfz-9bdYd159EH82buQcaPv4jSFgefjM',
    appId: '1:415358360776:android:3291dc0fbb5f8d7f8d59fd',
    messagingSenderId: '415358360776',
    projectId: 'food-delivery-69efb',
    storageBucket: 'food-delivery-69efb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4u50e5SRWC5n4nZGad2hTtLvHWfoTKgI',
    appId: '1:181239189384:ios:dfadb641d045c3697a343d',
    messagingSenderId: '181239189384',
    projectId: 'fooddeliveryapp-785a0',
    storageBucket: 'fooddeliveryapp-785a0.appspot.com',
    iosClientId: '181239189384-66500bhv19bfl308qvuc8tnof39u7et5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWebPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4u50e5SRWC5n4nZGad2hTtLvHWfoTKgI',
    appId: '1:181239189384:ios:dfadb641d045c3697a343d',
    messagingSenderId: '181239189384',
    projectId: 'fooddeliveryapp-785a0',
    storageBucket: 'fooddeliveryapp-785a0.appspot.com',
    iosClientId: '181239189384-66500bhv19bfl308qvuc8tnof39u7et5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWebPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDMvw1aJ2xISCvZVifdj2ws_CqCYti-gY',
    appId: '1:415358360776:web:ee10e90d88e1f0838d59fd',
    messagingSenderId: '415358360776',
    projectId: 'food-delivery-69efb',
    authDomain: 'food-delivery-69efb.firebaseapp.com',
    storageBucket: 'food-delivery-69efb.appspot.com',
  );

}