name: seller_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0

  image_picker: ^0.8.7+1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  shared_preferences: ^2.1.0
  flutter_staggered_grid_view: ^0.4.1
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  flutter_smart_dialog: ^4.9.8+1
  flutter_riverpod: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
         
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_aa.png
  image_web: assets/images/splash_aa.png
  android: true
  ios: true
  web: true
  android_12:
  #dart run flutter_native_splash:create
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon_aa.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon_aa.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  #    flutter pub run flutter_launcher_icons